name: tasks
imports:
  - https://get.silverbullet.md/global.plug.json
syntax:
  DeadlineDate:
    firstCharacters:
      - "📅"
    regex: "📅\\s*\\d{4}\\-\\d{2}\\-\\d{2}"
    styles:
      backgroundColor: "rgba(22,22,22,0.07)"
  CompletedDate:
    firstCharacters:
      - "✅"
    regex: "✅\\s*\\d{4}\\-\\d{2}\\-\\d{2}"
    styles:
      backgroundColor: "rgba(22,22,22,0.07)"
  RepeatInterval:
    firstCharacters:
      - "🔁"
    regex: "🔁\\s*every\\s+\\w+"
    styles:
      backgroundColor: "rgba(22,22,22,0.07)"
functions:
  turnIntoTask:
    redirect: core.applyLineReplace
    slashCommand:
      name: task
      description: Turn into task
      match: "^(\\s*)[\\-\\*]?\\s*(\\[[ xX]\\])?\\s*"
      replace: "$1* [ ] "

  indexTasks:
    path: "./task.ts:indexTasks"
    events:
      - page:index
  taskToggle:
    path: "./task.ts:taskToggle"
    events:
      - page:click
  itemQueryProvider:
    path: ./task.ts:queryProvider
    events:
      - query:task
  taskToggleCommand:
    path: ./task.ts:taskToggleCommand
    command:
      name: "Task: Toggle"
      key: Alt-t
      contexts:
        - Task
  taskPostponeCommand:
    path: ./task.ts:postponeCommand
    command:
      name: "Task: Postpone"
      key: Alt-+
      contexts:
        - DeadlineDate
  previewTaskToggle:
    env: client
    path: ./task.ts:previewTaskToggle
    events:
      - preview:click